---
  - name: Fetch webuzo
    ansible.builtin.get_url:
      url: http://files.webuzo.com/install.sh
      dest: /home
      mode: 0755
      force: yes
      validate_certs: false
    when: webuzo_installed is not defined

  - name: Install webuzo
    command: chdir=/home ./install.sh --install=apache2,nodejs,nodejs14,nodejs16,nodejs17,nodejs18,nodejs19,mariadb109,mongodb,pgsql,php81,php80,php74,perl,python2,python3,bind,exim,dovecot,pureftpd,jailshell,django,passenger,csf,Imunify360
    async: 1200 #wait for upto 20 minutes
    poll: 120 #check every 2 minutes
    register: webuzo_install_completed
    when: webuzo_installed is not defined