---
  - name: Check wheather webuzo is installed
    stat:
      path: '/usr/local/webuzo'
    register: webuzo_check
    check_mode: no
    failed_when: false
    changed_when: false

  - name: Register webuzo_installed variable
    set_fact:
      webuzo_installed: true
    when: webuzo_check.stat.exists

  - name: Prepare and config the server
    include_tasks: basic-config.yaml
  
  - name: Installing webuzo
    include_tasks: install-webuzo.yaml
    when: webuzo_installed is not defined

  - name: Setup PHP.ini config
    include_tasks: php.yaml

  - name: Copy Hositng Packages
    include_tasks: hostingplans.yaml

  - name: Copy Custom Configuration file
    include_tasks: custom-config.yaml
