---
  - name: CSF | disable firewall testing mode on CSF config
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "^TESTING ="
      line: 'TESTING = "0"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | change usermem from 512 to 0
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "PT_USERMEM ="
      line: 'PT_USERMEM = "0"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Disable SSH Email Alert
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "LF_SSH_EMAIL_ALERT ="
      line: 'LF_SSH_EMAIL_ALERT = "0"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Configure incomming TCP ports
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "TCP_IN ="
      line: 'TCP_IN = "20,21,22,25,53,80,110,143,443,465,587,993,995,1157,2002,2003,2004,2005,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,3306,49152:65534,8443,8080"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Cofigure outgoing TCP Ports
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "TCP_OUT ="
      line: 'TCP_OUT = "20,21,22,25,37,43,53,80,110,113,143,443,465,587,873,993,995,2002,2003,2004,2005,2083,2086,2087,2089,2703,27017,3306,8080"' # 27017 port opended for MongoDB outogoing remote connection as https://www.namecheap.com/support/knowledgebase/article.aspx/10544/22/do-you-support-mongodb/
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Cofigure UDP Ports
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "{{ item.search }}"
      line: "{{ item.replace }}"
    notify: 
      - Restart CSF
      - Restart LFD
    with_items:
      - { search: "UDP_OUT =", replace: 'UDP_OUT = "20,21,53,113,123,873,6277,24441,33434:33523"' }
      - { search: "UDP_IN =", replace: 'UDP_IN = "20,21,53,80,443,51820"' }
  - name: CSF | RESTRICT_SYSLOG from 0 to 3
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "RESTRICT_SYSLOG ="
      line: 'RESTRICT_SYSLOG = "3"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Disable Permanent block alert
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "LF_PERMBLOCK_ALERT ="
      line: 'LF_PERMBLOCK_ALERT = "0"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Disable email alert
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "LF_EMAIL_ALERT ="
      line: 'LF_EMAIL_ALERT = "0"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | PT_UserTIME change to 0
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "PT_USERTIME ="
      line: 'PT_USERTIME = "0"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Disable Temp Email Alert
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "LF_TEMP_EMAIL_ALERT ="
      line: 'LF_TEMP_EMAIL_ALERT = "0"'
    notify: 
      - Restart CSF
      - Restart LFD
  - name: whitelisting IPs on CSF
    blockinfile:
      block: |
        27.147.204.199 # My Home IP
      state: present
      path: /etc/csf/csf.allow
    notify: 
      - Restart CSF
      - Restart LFD
  - name: CSF | Extend cPanel login failure limit
    lineinfile:
      dest: "/etc/csf/csf.conf"
      regexp: "LF_IMAPD ="
      line: 'LF_IMAPD = "10"'
    notify:
      - Restart CSF
      - Restart LFD
